name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies and build locally (optional)
      run: |
        npm install
        npm run build

    - name: Deploy to server via SSH
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.SERVER_HOST }}
        port: ${{ secrets.SERVER_PORT }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
         APP_DIR=~/Apartments

         # שמירת תיקיית public
         if [ -d "$APP_DIR/public" ]; then
         echo "שומר את תיקיית public"
         cp -r $APP_DIR/public /tmp/public_backup
         fi

         # הורדת הקוד החדש
         rm -rf /tmp/apartments_new
         git clone https://github.com/MalkiAnshin/Apartments.git /tmp/apartments_new

         # מחיקת הקבצים הקיימים *למעט public*
         find $APP_DIR -mindepth 1 -maxdepth 1 ! -name public -exec rm -rf {} \;

         # העתקת הקבצים החדשים למיקום הקיים
         cp -r /tmp/apartments_new/* $APP_DIR/

         # שחזור public
         if [ -d "/tmp/public_backup" ]; then
         echo "משחזר את תיקיית public"
         cp -r /tmp/public_backup/* $APP_DIR/public/
         fi

          # יצירת קובץ .env עם משתנים מהסודות
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env

          # התקנת תלויות ובנייה
          npm install
          npm run build

          # הפעלה מחדש של האפליקציה
          pm2 delete all || true
          pm2 start npm --name "apartments-app" -- run start